version: '2'
services:
  redis:
    image: redis
    ports:
      - "6379:6379"
    networks:
      - nginx-auth
  nginx:
    build: .
    environment:
      - CLIENT_CACHE_REFRESH_INTERVAL=3
      - JWT_SECRET=secret
    ports:
      - "80:80"
    volumes:
      - ./nginx/conf:/opt/openresty/nginx/conf
      - ./scripts:/opt/openresty/nginx/scripts
    networks:
      - nginx-auth
    depends_on:
      - redis
networks:
  nginx-auth:
